### ISSUE TITLE
Add support for IRC tags (Needed for Twitch)

### ISSUE THREAD

**Issue by jpcguy89** [ahyattdev/OrangeIRC#1]
Hi,

I've been using OrangeIRC for my app and I love it! There is one problem, however. I need to access the tags from the messages and I'm not sure how to do so using OrangeIRC or if it's even possible. Could you help me figure it out? Here's a link to the API that describes the tags:

https://dev.twitch.tv/docs/v5/guides/irc/ (See 'Bits message', 'Normal Message' listed under "PRIVMSG". There's several of them but only one shows the Normal/Bits Message information.)

**Comment by ahyattdev** [comment]
I'm glad you are interested in OrangeIRC. 

The page you linked mentions IRCv3, which is a newer version of the IRC protocol that OrangeIRC does not currently support. 

Apparently, the data that you need is in a special format, which comes before the `PRIVMSG` command. I am not sure what standard they are from, maybe IRCv3, maybe custom to Twitch. They appear to be attributes, and parsing them also looks to be straightforward. It just starts with an @ symbol and is in key=value;otherkey=value format, so adding support to the [message parser](https://github.com/ahyattdev/OrangeIRC/blob/master/OrangeIRC%20Core/Message.swift) should be easy. 

Here they are, at the front of PRIVMSG commands:
`@badges=global_mod/1,turbo/1;color=#0D4200;display-name=TWITCH_UserNaME;emotes=25:0-4,12-16/1902:6-10;mod=0;room-id=1337;subscriber=0;turbo=1;user-id=1337;user-type=global_mod`

I would add support for this now, but I am visiting family for the holidays and won't have the resources needed to program for about a week. In the meantime, feel free to submit a pull request adding this feature if you want. 

You may run into other issues using `OrangeIRCCore` with Twitch's IRC servers, as they appear to use IRCv3 and other custom stuff. OrangeIRC currently aims to fully support [RFC 1459](https://tools.ietf.org/html/rfc1459), [RFC 2812](https://tools.ietf.org/html/rfc2812), and IRCv3, in that order. This isn't set in stone, and Twitch stuff could be added. Let me know if there are any specific commands Twitch needs.

**Comment by ahyattdev** [comment]
Support added in b0b52e5. 

The best I could do to verify that this works is make a unit test for it, but it may be different in the wild. Every instance of `Message` should now have a `tags` property, which is an array of `Tag` values. 

Tag is defined as:

`typealias Tag = (key: String, value: String?, vendor: String?)`

The `tags` array can have zero of more `Tag`s. 

`value` is an optional because according to the specification and the Twitch examples it can be empty. I didn't notice `vendor` being mentioned in the Twitch examples, but I added support for it anyway because the IRCv3 documentation mentions it. 

Let me know if this helps.
